# Generated by Django 3.2.5 on 2021-07-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rent',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rent_day',
            new_name='discount_for',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Discount', 'Discount'), ('Sold', 'Sold')], max_length=100, null=True),
        ),
    ]
